### ISSUE TITLE
Duplicate 'Content' items were included

### ISSUE THREAD

**Issue by haseeb9922** [TrackableEntities/Demo.UrfCore3#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1022	Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Properties\launchSettings.json'	Demo.UrfCore3.Api	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	316

**Comment by tonysneed** [comment]
Haven't been able to reproduce.
